spring.application.name=crud_spring
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=32sMp20SD1faqporcdk2005ocPS76POs
